spring:
  application:
    name: moin-challenge
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sangMoon
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: user
      password: "$2a$10$l49YJqdf5NVX7IeBYWNS6eYTfaLPGd7V1m.YLa1cZzghBPqlOQPjS"

springdoc:
  api-docs:
    path: /api-docs
    enabled : true

  swagger-ui:
    enabled: true
    path: swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true

jwt:
  secretKey: "QyNvbmc4aW9ucyYteW91LXdFcmUtYWxsLTEhbDBuMiE="
  expiration: 1800000

encryption:
  secretKey : "LSNCZXlvbmQtdGhlLW1vb24jMDchMjJCYUNFU1NLRVk="